const groupedParties = {
  1: ["Masum", "Insaf"],
  2: ["Rahim", "Titi", "Mahdi", "Manha", "Maliha"],
  3: ["Sakif", "Tasneem"],
  4: ["Sovon", "Mr. Nizam", "Suiba"],
  5: ["Sefath", "Sefath +1"],
  6: ["Babli", "Mrs. Hasan", "Arnab", "Erin"],
  7: ["Lucky", "Mukit", "Mukit's Dad"],
  8: ["Dipu", "Husband of Dipu"],
  9: ["Shawn", "Samiha"],
  10: ["Rafid", "Mr. Khokon", "Mrs. Rehana", "Saif", "Jarif", "Dalia"],
  11: ["Asibul", "Laisa", "Arad", "Mr. Hoque", "Mrs. Ayesha"],
  12: ["Nupur", "Mr. Rahman", "Walid", "Anand"],
  13: ["Patwary", "Mrs. Patwary", "Ayesha"],
  14: ["Nasima", "Mohammed"],
  15: ["Mr. Shahnewaz", "Mrs. Dalia", "Rafa", "Luba"],
  16: ["Nasif", "Sumaiya", "Mr. Fukrullah"],
  17: [
    "Pavel",
    "Jenita",
    "Zafeer",
    "Zayeer",
    "Mr. Shah Alam",
    "Mr. Jewel",
    "Mr. Anwar Khan",
    "Mrs. Parul Akhter",
    "Mr. Onik",
  ],
  18: ["Zahir", "Mita", "Zahin"],
  19: ["Uzzal", "Mother of Uzzal", "Tusi", "Gibran"],
  20: ["Ziggy", "Mr. Abul", "Mrs. Fatema"],
  21: ["Afrim", "Edona"],
  22: ["Daniel", "Victoria"],
  23: ["Niko"],
  24: ["Gabe"],
  25: ["Rez"],
  26: ["Syed", "Syed +1"],
  27: ["Usman", "Aisha", "Alaiha", "Alizeh", "Aryan", "Azmeer"],
  28: ["Shaj", "Lubaba"],
  29: [
    "Yousef",
    "Ayesha",
    "Son of Yousef",
    "Mother of Yousef",
    "Father of Yousef",
    "Sister of Yousef",
    "Nephew of Yousef",
  ],
  30: [
    "Tanzila",
    "Mamun",
    "Mrs. Khuki",
    "Mr. Ullah",
    "Taheem",
    "Tahreen",
    "Tafheez",
  ],
  31: ["Shamsul", "Julie", "Mr. Ijaz"],
  32: ["Rahin", "Arfa"],
  33: ["Tahmina", "Jahnie", "Mr. Ilan"],
  34: ["Priya", "Moshiur"],
};

export default groupedParties;
