const groupedParties = {
  1: ['Masum', 'Insaf'],
  2: ['Rahim', 'Titi', 'Mahdi', 'Manha', 'Maliha'],
  3: ['Sakif', 'Tasneem'],
  4: ['Sovon', 'Nizam', 'Suiba'],
  5: ['Sefath', 'Sefath +1'],
  6: ['Babli', 'Mr. Hasan','Arnab', 'Erin'],
  7: ['Lucky', 'Mukit', "Mukit's Dad"],
  8: ['Dipu', 'Husband of Dipu'],
  9: ['Shawn', 'Samiha'],
  10: ['Rafid', 'Mr. Khokon', 'Mrs. Rehana', 'Saif'],
  11: ['Asibul', 'Laisa', 'Arad', 'Mr. Hoque', 'Mrs. Ayesha'],
  12: ['Nupur', 'Mr. Rahman', 'Walid', 'Anand'],
  13: ['Patwary', 'Mrs. Patwary', 'Ayesha'],
  14: ['Nasima', 'Mohammed'],
  15: ['Mr. Shahnewaz', 'Mrs. Dalia', 'Rafa', 'Luba'],
  16: ['Nasif', 'Sumaiya', 'Mr. Fukrullah'],
  17: ['Pavel', 'Jenita', 'Zafeer', 'Zayeer', 'Mr. Shah Alam', 'Mr. Jewel', 'Mr. Anwar Khan', 'Mrs. Parul Akhter'],
  18: ['Zahir', 'Mita', 'Zahin'],
  19: ['Uzzal', 'Tusi', 'Gibran'],
  20: ['Ziggy', 'Mr. Abul', 'Mrs. Fatema'],
  21: ['Afrim', 'Edona'],
  22: ['Daniel', 'Victoria'],
  23: ['Niko'],
  24: ['Gabe'],
  25: ['Rez'],
  26: ['Syed', 'Refa'],
  27: ['Usman', 'Aisha', 'Alaiha', 'Alizeh', 'Aryan'],
  28: ['Shaj', 'Lubaba'],
  29: ['Monu Apa'],
  30: ['Tanzila', 'Mamun', 'Mrs. Khuki', 'Mr. Ullah', 'Taheem', 'Tahreen', 'Tafheez'],
  31: ['Shamsul', 'Julie', 'Mr. Ijaz'],
  32: ['Rahin', 'Arfa'],
  33: ['Ruby Apa', 'Ruby Son'],
  34: ['Tahmina', 'Jahnie', 'Mr. Ilan'],
  35: ['Priya', 'Moshiur'],
  36: ['Sherin', 'Kerwin'],
  37: ['Mahwiyat', 'Arif'],
  38: ['Sufer', 'Fatima', 'Jan', 'Jamin'],
  39: ['Rukeya', 'Akbar', 'Tahmim', 'Nasim'],
  40: ['Gulshanara', 'Maiz'],
  41: ['Basith', 'Shamima', 'Mahira', 'Maisha', 'Suhan'],
  42: ['Khaled'],
  43: ['Saif'],
  44: ['Ayon'],
  45: ['Nash'],
  46: ['Navid'],
  47: ['Fazle'],
  48: ['Shahara'],
  49: ['Tabby']
};
